name: man_on
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_polygon: ^0.3.0+2
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.17.3
  flutter_form_builder: ^9.2.1
  cupertino_icons: ^1.0.6
  form_builder_validators: ^9.1.0
  remedi_kopo: ^0.0.2
  http: ^1.2.1

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ground.png
