// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTDcz7hfgzmojOaWE3CNBsguTFh2L2nQE',
    appId: '1:633751258771:web:8d3b595b20102243822f66',
    messagingSenderId: '633751258771',
    projectId: 'man-on',
    authDomain: 'man-on.firebaseapp.com',
    storageBucket: 'man-on.appspot.com',
    measurementId: 'G-CMSRJHS060',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFMV5haKPDGuhlFXUT89f780-z5KuVSBI',
    appId: '1:633751258771:android:29528d200ea90745822f66',
    messagingSenderId: '633751258771',
    projectId: 'man-on',
    storageBucket: 'man-on.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmqbhO7d3Lagpp32h__-pZk86phPKtrfY',
    appId: '1:633751258771:ios:3b6e7d715662e1a3822f66',
    messagingSenderId: '633751258771',
    projectId: 'man-on',
    storageBucket: 'man-on.appspot.com',
    iosBundleId: 'com.example.manOn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmqbhO7d3Lagpp32h__-pZk86phPKtrfY',
    appId: '1:633751258771:ios:3b6e7d715662e1a3822f66',
    messagingSenderId: '633751258771',
    projectId: 'man-on',
    storageBucket: 'man-on.appspot.com',
    iosBundleId: 'com.example.manOn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTDcz7hfgzmojOaWE3CNBsguTFh2L2nQE',
    appId: '1:633751258771:web:1d32a3285d8b4692822f66',
    messagingSenderId: '633751258771',
    projectId: 'man-on',
    authDomain: 'man-on.firebaseapp.com',
    storageBucket: 'man-on.appspot.com',
    measurementId: 'G-0WZBV5GLHY',
  );

}